spring.application.name: monitor-oiltank
spring.profiles.active: ${PROFILE:local}

server.port: ${SERVER_PORT:5001}

info:
  app.name: ${spring.application.name}
  app.version: ${version:project.version}
  app.profile: ${spring.profiles.active}

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info
  health.mongo.enabled: false

management.info:
  build.enabled: true
  env.enabled: true
  java.enabled: true
  os.enabled: true

logging.level:
  org.springframework: INFO

application.camera:
  #snapshotUrl: "rtsp://user:pass@192.168.1.10:554/stream1"
  #username: "user"
  #password: "pass"
  intervalSeconds: 10

application.level:
  minPercent: 20
  maxPercent: 95

application.mqtt:
  #brokerUrl: "tcp://localhost:1883"
  topic:
    level: "oil/level"
    alert: "oil/alert"